config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  resources :spreadsheets
  resources :users, only: [:show, :create, :edit]

  get '/logout', to: 'sessions#destroy'
  get '/show', to: 'users#show'
  get '/help', to: 'users#help'

end

app/models/spreadsheet.rb
class Spreadsheet < ActiveRecord::Base
  mount_uploader :csv, CsvUploader
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :spreadsheets
  accepts_nested_attributes_for :spreadsheets

  has_secure_password validations: false
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You have to log in to perform this action."
      redirect_to root_path
    end
  end

  def merge_csvs(path_to_folder)

    require 'csv'

    master = CSV.read("#{path_to_folder}/master.csv") # Reads in master 
    master.each {|each| each.push('')} # Adds another column to all rows
    Dir.glob("#{path_to_folder}/*.csv").each do |each| #Goes thru all csv files
      next if each == 'master.csv' # skips the master csv file
      file = CSV.read(each) # Reads in each file
      file.each do |line| #Goes thru each line of the file
        temp = master.assoc(line[0]) # Finds the appropriate line in master
        temp[-1] = line[1] if temp #updates last column if line is found
      end
    end

    csv = CSV.open("#{path_to_folder}/output.csv",'wb') #opens output csv file for writing
    master.each {|each| csv << each} #Goes thru modified master and saves it to file
    csv.close
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've logged in."
      redirect_to upload_path
    else
      flash[:error] = "There is something wrong with your username or password."
      redirect_to login_path
    end
  end

  def destroy
    User.find(session[:user_id]).destroy # delete user who logged out
    session[:user_id] = nil
    flash[:notice] = "You've logged out. Go ahead and merge more files if you want."
    redirect_to root_path

  end

end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  before_action :set_spreadsheet, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:create, :new]


  # GET /spreadsheets
  # GET /spreadsheets.json
  def index
    @spreadsheets = Spreadsheet.all
  end

  # GET /spreadsheets/1
  # GET /spreadsheets/1.json
  def show
  end

  # GET /spreadsheets/new
  def new
    @spreadsheet = Spreadsheet.new
  end

  # GET /spreadsheets/1/edit
  def edit
  end

  # POST /spreadsheets
  # POST /spreadsheets.json
  def create
    @spreadsheet = Spreadsheet.new(spreadsheet_params)

    respond_to do |format|
      if @spreadsheet.save
        format.html { redirect_to @spreadsheet, notice: 'Spreadsheet was successfully created.' }
        format.json { render :show, status: :created, location: @spreadsheet }
      else
        format.html { render :new }
        format.json { render json: @spreadsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spreadsheets/1
  # PATCH/PUT /spreadsheets/1.json
  def update
    respond_to do |format|
      if @spreadsheet.update(spreadsheet_params)
        format.html { redirect_to @spreadsheet, notice: 'Spreadsheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @spreadsheet }
      else
        format.html { render :edit }
        format.json { render json: @spreadsheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spreadsheets/1
  # DELETE /spreadsheets/1.json
  def destroy
    @spreadsheet.destroy
    respond_to do |format|
      format.html { redirect_to spreadsheets_url, notice: 'Spreadsheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spreadsheet
      @spreadsheet = Spreadsheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spreadsheet_params
      params.require(:spreadsheet).permit(:user_id, :csv)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_same_user, except: [:create, :new, :help, :show]

  def show
    @user = current_user
  end

  def new
    @user = User.new
    @spreadsheet = @user.spreadsheets.build
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      params[:spreadsheets]['csv'].each do |c|
        @spreadsheet = @user.spreadsheets.create(:csv => c)
      end
      flash[:notice] = "Your files have been merged!"
      redirect_to show_path 

    else
      render :new
    end

    #merge method from application_controller.rb
    merge_csvs("#{Rails.root}/public/uploads/spreadsheet/csv/#{@user.spreadsheets.first.user_id}")

  end

  def help
  end

  def user_params
    params.require(:user).permit(:email, :password, spreadsheets_attributes: [:id, :user_id, :csv])
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "You are not allowed to perform this action"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :error ? 'danger' : 'success' %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path%></li>
  <li><%= link_to "Help", help_path%></li>
   
   <% if !logged_in? %>
  <% else %>
  <li>
    <%= link_to "Logout", logout_path %>
  </li>
  <% end %>

  <% if !logged_in? %>
  <% else %>
  <li><%= link_to "New Merge", logout_path %></li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Merge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div> <!-- /container -->  
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-error span8">
      <h5>There were some errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/spreadsheets/_form.html.erb
<%= form_for(@spreadsheet) do |f| %>
  <% if @spreadsheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spreadsheet.errors.count, "error") %> prohibited this spreadsheet from being saved:</h2>

      <ul>
      <% @spreadsheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :csv %><br>
    <%= f.text_field :csv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spreadsheets/edit.html.erb
<h1>Editing Spreadsheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @spreadsheet %> |
<%= link_to 'Back', spreadsheets_path %>

app/views/spreadsheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Spreadsheets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Csv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spreadsheets.each do |spreadsheet| %>
      <tr>
        <td><%= spreadsheet.user_id %></td>
        <td><%= spreadsheet.csv %></td>
        <td><%= link_to 'Show', spreadsheet %></td>
        <td><%= link_to 'Edit', edit_spreadsheet_path(spreadsheet) %></td>
        <td><%= link_to 'Destroy', spreadsheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spreadsheet', new_spreadsheet_path %>

app/views/spreadsheets/new.html.erb
<h1>New Spreadsheet</h1>

<%= render 'form' %>

<%= link_to 'Back', spreadsheets_path %>

app/views/spreadsheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @spreadsheet.user_id %>
</p>

<p>
  <strong>Csv:</strong>
  <%= @spreadsheet.csv %>
</p>

<%= link_to 'Edit', edit_spreadsheet_path(@spreadsheet) %> |
<%= link_to 'Back', spreadsheets_path %>

app/views/users/help.html.erb
<div class="page-header">
  <h1>Help <small>Find out more about how this app works</small></h1>
</div>

<div class="row">
  <div class="col-md-8">

  <dl>
    <dt>What does this app do?</dt>
    <dd>This simple app takes spreadsheets in the .csv format and merges them into one spreadsheet. This can be useful if you have a spreadsheet with customer data and another spreadsheet with additional information (i.e. after sending them an email marketing campaign). To keep all your data in one spreadsheet you can use this app to merge the files instead of doing this manually or writing an Excel script. 
    </dd>
    <br>



      <div class="well well-lg">

        <table class="table table-bordered">
          <caption>master.csv</caption>
          <thead>
            <tr>
              <th>emails</th>
              <th>name</th>
              <th>address</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>email1@domain.com</td>
              <td>name1</td>
              <td>address1</td>
            </tr>
            <tr>
              <td>email2@domain.com</td>
              <td>name2</td>
              <td>address2</td>
            </tr>
            <tr>
              <td>email3@domain.com</td>
              <td>name3</td>
              <td>address3</td>
            </tr>
          </tbody>
        </table>

       <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>

        <table class="table table-bordered">
          <caption>status.csv</caption>
          <thead>
            <tr>
              <th>emails</th>
              <th>status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>email1@domain.com</td>
              <td>active</td>
            </tr>
            <tr>
              <td>email2@domain.com</td>
              <td>active</td>
            </tr>
            <tr>
              <td>email3@domain.com</td>
              <td>inactive</td>
            </tr>
          </tbody>
        </table>

      </div>


      <div class="well well-lg">

        <span class="glyphicon glyphicon-arrow-down" aria-hidden="true"></span>


        <table class="table table-bordered">
          <caption>output.csv</caption>
          <thead>
            <tr>
              <th>emails</th>
              <th>name</th>
              <th>address</th>
              <th>status</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>email1@domain.com</td>
              <td>name1</td>
              <td>address1</td>
              <td>active</td>
            </tr>
            <tr>
              <td>email2@domain.com</td>
              <td>name2</td>
              <td>address2</td>
              <td>active</td>
            </tr>
            <tr>
              <td>email3@domain.com</td>
              <td>name3</td>
              <td>address3</td>
              <td>inactive</td>
            </tr>
          </tbody>
        </table>

      </div>


    <br>
    <dt>How does it work?</dt>
    <dd>
    This app takes a master.csv spreadsheet and merges it with any number of addtional .csv spreadsheets you upload. 
      <ul>
        <li>Make sure your files are in the .csv format. Microsoft Excel and Google Spreadsheets let you export your files as .csv files. </li>
        <li>Make sure your main file is called master.csv The other files you want to merge with your master can have any name you want.</li>
        <li>Your files both need to have a first column with the same title (e.g. email). This column serves as the key to merge columns into the correct rows. 
        See our example files. Feel free to <a href = "https://www.dropbox.com/sh/crf1uu2k74jq6uy/AABC4s1eXKQWkMFafXxAx_zSa?dl=0">download the example files</a> and use them.</li>
      </ul> 
    </dd>

    <br>
    <dt>Is my data safe?</dt>
    <dd>Your data is merged and provided for download. It's not stored and data is deleted every 30 minutes. This whole project is open source and you can view the source code here: <a href = "http://github.com/neudabei/merge">Source Code on GitHub</a>
    </dd>

    <br>
    <dt>Is it free?</dt>
    <dd>Yes
    </dd>

    <br>
    <dt>Contact</dt>
    <dd>You can get in touch here if you have questions or comments: <a href = "mailto:rschultzejenaBEIgmailPUNKTcom" onclick = "this.href=this.href.replace(/BEI/,'&#64;').replace(/PUNKT/,'&#46;')">email</a>
    </dd>

  </dl>

  </div>
  <div class="col-md-4">
    
  </div>
</div>

app/views/users/merge.html.erb
Your files have been merged (merge.html.erb)

app/views/users/new.html.erb
<div class="page-header">
  <h1>Upload spreadsheets as .csv files <small>and download a merged version</small></h1>
</div>

<br>
<br>
<br>

<%= form_for(@user, :html => { :multipart => true }, class: 'form-signin') do |f| %>

<!--   <h2 class="form-signin-heading">Add your email and the files to merge.</h2>
 -->
   <div class="field">
     <%= f.label :email %><br>
     <%= f.text_field :email, class: 'form-control', placeholder: 'Enter your email'  %>
   </div>
   <br>
    <div class="field">
     <%= f.label :password %><br>
     <%= f.password_field :password, class: 'form-control', placeholder: 'Choose a password' %>
   </div>
   <br>
   <%= f.fields_for :spreadsheets do |s| %>
     <div class="field">
       <%= s.label :Drag_your_files_here %> <a href="help"><span class="glyphicon glyphicon-question-sign" aria-hidden="true" title="Read more about how this works in our help section."></span></a><br>
       <%= s.file_field :csv, :multiple => true, name: "spreadsheets[csv][]", class: 'form-control' %>
     </div>
   <% end %>
   <br>
   <div class="actions">
     <%= f.submit "Merge files!", class: "btn btn-lg btn-primary btn-block" %>
   </div>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>Your files were merged <small>and the result is ready for downloading</small></h1>
</div>

<br>
<h4>This is your merged file</h4>
<ul class="list-group">
  <li class="list-group-item"> <span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span> <%= link_to "Download the merged spreadsheet", "uploads/spreadsheet/csv/#{@user.spreadsheets.first.user_id}/output.csv" %> </li>
</ul>



<br>
<h4>These were the files you uploaded:</h4>

<ul class="list-group">
  <% @user.spreadsheets.each do |us| %>
    <li class="list-group-item"> <%= us.csv_identifier %> </li>
  <% end %>
</ul>